# Site settings
title: nfirvine.github.io blog
email: "'@'.join(['nfirvine']*2)+'.com'"
description: "DevOps, Ubuntu, and tech stuff"
baseurl: ""
url: "http://nfirvine.github.com"
username: nfirvine

# Build settings
markdown: kramdown
permalink: pretty
