# Site settings
title: blog.nfi.io
email: "nick@nfi.io"
description: "DevOps, Ubuntu, and tech stuff"
baseurl: ""
url: "http://blog.nfi.io"
username: nfirvine

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME

